<?php
require 'db.php';
require_login($pdo);
$user = current_user($pdo);
$rows = $pdo->query("SELECT species, location_label, COUNT(*) AS planted, SUM(CASE WHEN status='healthy' THEN 1 ELSE 0 END) AS survived FROM trees GROUP BY species, location_label ORDER BY planted DESC")->fetchAll();
$totalPlanted = 0; $totalSurvived = 0;
foreach ($rows as $row) { $totalPlanted += (int)$row['planted']; $totalSurvived += (int)$row['survived']; }
$rate = $totalPlanted ? round(($totalSurvived / $totalPlanted) * 100) : 0;
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Reports</title><style>body{margin:0;font-family:Arial,sans-serif;background:#f4f8f3;color:#18311c}.layout{display:grid;grid-template-columns:260px 1fr;min-height:100vh}.side{background:#19261c;color:#eef7ef;padding:22px}.side a{display:block;color:#d9e9d9;padding:11px 12px;border-radius:10px;text-decoration:none;margin-bottom:6px}.side a.active,.side a:hover{background:rgba(255,255,255,.1);color:#fff}.main{padding:24px}*{box-sizing:border-box}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:18px 0}.card{background:#fff;border:1px solid #dbe6da;border-radius:16px;padding:22px;box-shadow:0 10px 25px rgba(0,0,0,.05)}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:13px 10px;border-bottom:1px solid #e6eee5}@media(max-width:900px){.layout{grid-template-columns:1fr}.cards{grid-template-columns:1fr}}</style></head><body><div class="layout"><div class="side"><h2>Tree Keeper</h2><p><?= e($user['full_name']) ?></p><a href="dashboard.php">Dashboard</a><a href="trees.php">Trees</a><a href="add_tree.php">Add Tree</a><a href="tasks.php">Tasks</a><a class="active" href="reports.php">Reports</a><a href="map.php">Map</a><a href="tree_health.php">Health Check</a><a href="profile.php">Profile</a><a href="logout.php">Logout</a></div><div class="main"><h1>Reports</h1><p>Summary generated from MySQL data.</p><div class="cards"><div class="card"><div>Total Planted</div><h2><?= e($totalPlanted) ?></h2></div><div class="card"><div>Total Healthy</div><h2><?= e($totalSurvived) ?></h2></div><div class="card"><div>Survival Rate</div><h2><?= e($rate) ?>%</h2></div></div><div class="card"><table><thead><tr><th>Species</th><th>Location</th><th>Planted</th><th>Healthy</th><th>Rate</th></tr></thead><tbody><?php foreach ($rows as $row): ?><?php $rowRate = $row['planted'] ? round(($row['survived'] / $row['planted']) * 100) : 0; ?><tr><td><?= e($row['species']) ?></td><td><?= e($row['location_label']) ?></td><td><?= e($row['planted']) ?></td><td><?= e($row['survived']) ?></td><td><?= e($rowRate) ?>%</td></tr><?php endforeach; ?></tbody></table></div></div></div><script>console.log('Reports ready');</script></body></html>
